# Generated by Django 4.1.1 on 2022-09-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["manufacturer__name", "model"]},
        ),
    ]
