# Generated by Django 4.1.1 on 2022-10-18 18:57

from django.db import migrations, models
import taxi.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_manufacturer_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="uploads/cars/default_car_image.png",
                upload_to=taxi.models.car_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="logo",
            field=models.ImageField(
                default="uploads/manufacturers/empty_logo.png",
                upload_to=taxi.models.manufacturer_image_file_path,
            ),
        ),
    ]
